# 1. Import Numpy and Import Txt File

In [1]:
import numpy as np
world_alcohol = np.genfromtxt('01_world_alcohol.txt', delimiter = ',', dtype = str) 
print(world_alcohol)

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


# 2. Create Vector

In [2]:
# Solution 1: directly input elements
import numpy as np
vector_1 = np.array([5, 10, 15, 20])    
print(vector_1)

[ 5 10 15 20]


In [3]:
# Solution 2: use np.arange(start, end, step), not including end
vector_2 = np.arange(5, 25, 5)          
print(vector_2)

[ 5 10 15 20]


In [4]:
# Solution 3: use np.linspace(start, end, number of element), including end
vector_3 = np.linspace(5, 20, 4)          
print(vector_3)

[ 5. 10. 15. 20.]


In [5]:
# Solution 4: use np.linspace(start, end, number of element), including end
vector_4 = np.linspace(5, 20, 4, dtype = int)          
print(vector_4)

[ 5 10 15 20]


# 3. Create Matrix

In [6]:
# Solution 1: directly input elements, but note we got more brackets
matrix_1 = np.array([[5, 10, 15, 20], 
                     [10, 15, 20, 25]])
print(matrix_1)

[[ 5 10 15 20]
 [10 15 20 25]]


In [7]:
# Solution 2: use np.arange(n).reshape(rows, columns), n = rows * columns
matrix_2 = np.arange(15).reshape(3, 5)
print(matrix_2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
# Solution 3: use np.random.rand()
matrix_3 = np.random.rand(3, 4)
print(matrix_3)

[[0.76326938 0.96739843 0.49451517 0.58993813]
 [0.32843097 0.34341433 0.21367375 0.25334452]
 [0.98154578 0.28294621 0.64178334 0.85354203]]


In [9]:
# Solution 4: np.ones() or np.zeros(), note we got one more bracket inside
matrix_4 = np.zeros((3, 4))
print(matrix_4)

matrix_5 = np.ones((3, 4))
print(matrix_5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 4. Basic Properties of Vector

In [10]:
vector = np.array([1, 2, 3, 4, 5])
print(vector)

[1 2 3 4 5]


In [11]:
print(vector.shape)

(5,)


In [12]:
print(vector.size)

5


In [13]:
print(vector.dtype)

int32


In [14]:
print(vector.ndim)

1


In [15]:
print(vector.min())

1


In [16]:
print(vector.max())

5


In [17]:
print(vector.sum())

15


# 5. Basic Properties of Matrix

In [18]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [19]:
print(matrix.shape)

(2, 3)


In [20]:
print(matrix.size)

6


In [21]:
print(matrix.dtype)

int32


In [22]:
print(matrix.ndim)

2


In [23]:
print(matrix.min())
print(matrix.min(axis = 0))
print(matrix.min(axis = 1))

1
[1 2 3]
[1 4]


In [24]:
print(matrix.max())
print(matrix.max(axis = 0))
print(matrix.max(axis = 1))

6
[4 5 6]
[3 6]


In [25]:
print(matrix.sum())
print(matrix.sum(axis = 0))
print(matrix.sum(axis = 1))

21
[5 7 9]
[ 6 15]


# 6. Access Vector

In [26]:
vector = np.array([1, 2, 3, 4, 5])
print(vector)

[1 2 3 4 5]


In [27]:
print(vector[0])
print(vector[2])
print(vector[-1])
print(vector[0:3])

1
3
5
[1 2 3]


# 7. Access Matrix

In [28]:
matrix = np.array([[1, 2, 3], [0, 5, 4], [9, 2, 5]])
print(matrix)

[[1 2 3]
 [0 5 4]
 [9 2 5]]


In [29]:
print(matrix[:])

[[1 2 3]
 [0 5 4]
 [9 2 5]]


In [30]:
print(matrix[0:2, 1:3])          # print(matrix[rows, columns])
print(matrix[1, 2])

[[2 3]
 [5 4]]
4


In [31]:
print(matrix.argmax(axis = 0))   # return the index of max or min by columns
print(matrix.argmin(axis = 0))

[2 1 2]
[1 0 0]


In [32]:
print(matrix.argmax(axis = 1))   # return the index of max or min by rows
print(matrix.argmin(axis = 1))

[2 1 0]
[0 0 1]


In [33]:
index = matrix.argmax(axis = 0)
print(index)
max_by_columns = matrix[index]   # Get elements in the row where the maximum is located
print(max_by_columns)

[2 1 2]
[[9 2 5]
 [0 5 4]
 [9 2 5]]


In [34]:
index = matrix.argmax(axis = 0)
print(index)
max_by_columns = matrix[index, range(matrix.shape[1])]
print(max_by_columns)

[2 1 2]
[9 5 5]


# 8. Change Matrix

In [35]:
matrix = np.array([[1,2], [5,6], [4,9]])
print(matrix)

[[1 2]
 [5 6]
 [4 9]]


In [36]:
print(matrix.T)

[[1 5 4]
 [2 6 9]]


In [37]:
print(np.tile(matrix, (2,3)))

[[1 2 1 2 1 2]
 [5 6 5 6 5 6]
 [4 9 4 9 4 9]
 [1 2 1 2 1 2]
 [5 6 5 6 5 6]
 [4 9 4 9 4 9]]


In [38]:
print(np.sort(matrix, axis = 0))

[[1 2]
 [4 6]
 [5 9]]


In [39]:
matrix.sort(axis = 0)
print(matrix)

[[1 2]
 [4 6]
 [5 9]]


In [40]:
matrix = np.arange(15)
print(matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [41]:
print(matrix.reshape(3,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [42]:
print(matrix.reshape(3,5).ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [43]:
print(np.floor(10 * np.random.rand(3,4)))

[[2. 5. 1. 3.]
 [7. 2. 2. 3.]
 [9. 0. 6. 8.]]


In [44]:
print(np.ceil(np.random.rand(3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [45]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
print(np.hstack((A,B)))
print(np.vstack((A,B)))

[[1 1 2 0]
 [0 1 3 4]]
[[1 1]
 [0 1]
 [2 0]
 [3 4]]


In [46]:
matrix = np.random.rand(2,6)
print(matrix)

[[0.09288353 0.45906919 0.70849874 0.44475526 0.55785714 0.2656046 ]
 [0.4469312  0.68864206 0.00766778 0.617853   0.2274757  0.38887036]]


In [47]:
print(np.hsplit(matrix, 3))        # split matrix into 3 parts in horizontal direction

[array([[0.09288353, 0.45906919],
       [0.4469312 , 0.68864206]]), array([[0.70849874, 0.44475526],
       [0.00766778, 0.617853  ]]), array([[0.55785714, 0.2656046 ],
       [0.2274757 , 0.38887036]])]


In [48]:
print(np.hsplit(matrix, (3,4)))    # split matrix in the 3rd and 4th space in horizontal direction

[array([[0.09288353, 0.45906919, 0.70849874],
       [0.4469312 , 0.68864206, 0.00766778]]), array([[0.44475526],
       [0.617853  ]]), array([[0.55785714, 0.2656046 ],
       [0.2274757 , 0.38887036]])]


# 9. Mathematic Operation

In [49]:
A = np.array([20, 39, 40, 50])
B = np.arange(4)
print('A:', A)
print('B:', B)

A: [20 39 40 50]
B: [0 1 2 3]


In [50]:
print('A - B = ', A - B)

A - B =  [20 38 38 47]


In [51]:
print('A - 1 = ', A - 1)

A - 1 =  [19 38 39 49]


In [52]:
print('B ^ 2 = ', B ** 2)

B ^ 2 =  [0 1 4 9]


In [53]:
print('e ^ B = ', np.exp(B))

e ^ B =  [ 1.          2.71828183  7.3890561  20.08553692]


In [54]:
print('sqrt(B) = ', np.sqrt(B))

sqrt(B) =  [0.         1.         1.41421356 1.73205081]


In [55]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
print(A * B)                     # multiplication of corresponding elements

[[2 0]
 [0 4]]


In [56]:
print(A.dot(B))                  # matrix multiplicaiton

[[5 4]
 [3 4]]


In [57]:
print(np.dot(A,B))

[[5 4]
 [3 4]]


# 10. Logistic Operation

In [58]:
vector = np.array([5, 10, 15, 20])
print(vector)

[ 5 10 15 20]


In [59]:
print(vector == 10)

[False  True False False]


In [60]:
print((vector == 10) & (vector == 15))

[False False False False]


In [61]:
print((vector == 10) | (vector == 15))

[False  True  True False]


In [62]:
equal_to_10 = (vector == 10)
print(equal_to_10)

[False  True False False]


In [63]:
print(vector[equal_to_10])

[10]


In [64]:
matrix = np.array([[1,3], [2,5], [9,0]])
print(matrix)

[[1 3]
 [2 5]
 [9 0]]


In [65]:
second_column_5 = (matrix[:,1] == 5)
print(second_column_5)

[False  True False]


In [66]:
print(matrix[second_column_5, :])

[[2 5]]
