# Import Numpy and Import Txt File

In [1]:
import numpy as np
world_alcohol = np.genfromtxt('01_world_alcohol.txt', delimiter = ',', dtype = str) 
print(world_alcohol)

# Create Vector

In [2]:
# Solution 1: directly input elements
import numpy as np
vector_1 = np.array([5, 10, 15, 20])    
print(vector_1)

In [3]:
# Solution 2: use np.arange(start, end, step), not including end
vector_2 = np.arange(5, 25, 5)          
print(vector_2)

In [4]:
# Solution 3: use np.linspace(start, end, number of element), including end
vector_3 = np.linspace(5, 20, 4)          
print(vector_3)

In [5]:
# Solution 4: use np.linspace(start, end, number of element), including end
vector_4 = np.linspace(5, 20, 4, dtype = int)          
print(vector_4)

[ 5 10 15 20]


In [6]:
array = [1] * 10
print(array)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


# Create Matrix

In [7]:
# Solution 1: directly input elements, but note we got more brackets
matrix_1 = np.array([[5, 10, 15, 20], 
                     [10, 15, 20, 25]])
print(matrix_1)

[[ 5 10 15 20]
 [10 15 20 25]]


In [8]:
# Solution 2: use np.arange(n).reshape(rows, columns), n = rows * columns
matrix_2 = np.arange(15).reshape(3, 5)
print(matrix_2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [9]:
# Solution 3: use np.random.rand()
matrix_3 = np.random.rand(3, 4)
print(matrix_3)

[[0.44608494 0.23331789 0.89478749 0.59419062]
 [0.03576711 0.95407134 0.48378911 0.22327061]
 [0.29945709 0.99883063 0.34168078 0.99598931]]


In [10]:
# Solution 4: np.ones() or np.zeros(), note we got one more bracket inside
matrix_4 = np.zeros((3, 4))
print(matrix_4)

matrix_5 = np.ones((3, 4))
print(matrix_5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Basic Properties of Vector

In [11]:
import numpy as np

In [12]:
vector = np.array([1, 2, 3, 4, 5])
print(vector)

[1 2 3 4 5]


In [13]:
vector = np.array([1, 2, 3, 4, 5])
print(type(vector))

<class 'numpy.ndarray'>


In [14]:
print(vector.shape)

(5,)


In [15]:
print(vector.size)

5


In [16]:
print(vector.dtype)     # int32, float64, string

int32


In [17]:
print(vector.ndim)

1


In [18]:
print(vector.min())

1


In [19]:
print(vector.max())

5


In [20]:
print(vector.sum())

15


# Basic Properties of Matrix

In [21]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [22]:
print(matrix.shape)

(2, 3)


In [23]:
print(matrix.size)

6


In [24]:
print(matrix.dtype)

int32


In [25]:
print(matrix.ndim)

2


In [26]:
print(matrix.min())
print(matrix.min(axis = 0))   # axis = 0 by column
print(matrix.min(axis = 1))   # axis = 1 by row

1
[1 2 3]
[1 4]


In [27]:
print(matrix.max())
print(matrix.max(axis = 0))
print(matrix.max(axis = 1))

6
[4 5 6]
[3 6]


In [28]:
print(matrix.sum())
print(matrix.sum(axis = 0))
print(matrix.sum(axis = 1))

21
[5 7 9]
[ 6 15]


# Access Vector
- Index and Slice
- array[row]  ==  array[row, :]
- array[row][column]
- array[row, column]

In [29]:
vector = np.array([1, 2, 3, 4, 5])
print(vector)

[1 2 3 4 5]


In [30]:
print(vector[0])
print(vector[2])
print(vector[-1])
print(vector[0:3])

1
3
5
[1 2 3]


# Access Matrix
- Index and Slice
- array[row]  ==  array[row, :]
- array[row][column]
- array[row, column]

In [31]:
matrix = np.array([[1, 2, 3], [0, 5, 4], [9, 2, 5]])
print(matrix)

[[1 2 3]
 [0 5 4]
 [9 2 5]]


In [32]:
print(matrix[:])

[[1 2 3]
 [0 5 4]
 [9 2 5]]


In [33]:
print(matrix[0:2, 1:3])          # print(matrix[rows, columns])
print(matrix[1, 2])

[[2 3]
 [5 4]]
4


In [34]:
print(matrix.argmax(axis = 0))   # return the index of max or min by columns
print(matrix.argmin(axis = 0))

[2 1 2]
[1 0 0]


In [35]:
print(matrix.argmax(axis = 1))   # return the index of max or min by rows
print(matrix.argmin(axis = 1))

[2 1 0]
[0 0 1]


In [36]:
index = matrix.argmax(axis = 0)
print(index)
max_by_columns = matrix[index]   # Get elements in the row where the maximum is located
print(max_by_columns)

[2 1 2]
[[9 2 5]
 [0 5 4]
 [9 2 5]]


In [37]:
index = matrix.argmax(axis = 0)
print(index)
max_by_columns = matrix[index, range(matrix.shape[1])]
print(max_by_columns)

[2 1 2]
[9 5 5]


# Change Matrix

In [38]:
matrix = np.array([[1,2], [5,6], [4,9]])
print(matrix)

[[1 2]
 [5 6]
 [4 9]]


In [39]:
print(matrix.T)

[[1 5 4]
 [2 6 9]]


In [40]:
print(np.tile(matrix, (2,3)))

[[1 2 1 2 1 2]
 [5 6 5 6 5 6]
 [4 9 4 9 4 9]
 [1 2 1 2 1 2]
 [5 6 5 6 5 6]
 [4 9 4 9 4 9]]


In [41]:
print(np.sort(matrix, axis = 0))

[[1 2]
 [4 6]
 [5 9]]


In [42]:
matrix.sort(axis = 0)
print(matrix)

[[1 2]
 [4 6]
 [5 9]]


In [43]:
matrix = np.arange(15)
print(matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [44]:
print(matrix.reshape(3,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [45]:
print(matrix.reshape(3,5).ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [46]:
print(np.floor(10 * np.random.rand(3,4)))

[[9. 0. 1. 3.]
 [8. 0. 2. 7.]
 [0. 6. 0. 6.]]


In [47]:
print(np.ceil(np.random.rand(3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [48]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
print(np.hstack((A,B)))
print(np.vstack((A,B)))

[[1 1 2 0]
 [0 1 3 4]]
[[1 1]
 [0 1]
 [2 0]
 [3 4]]


In [49]:
matrix = np.random.rand(2,6)
print(matrix)

[[0.68946336 0.18540372 0.84345207 0.61759125 0.4296455  0.53713882]
 [0.52254447 0.21027979 0.42146907 0.15173056 0.43080623 0.32991653]]


In [50]:
import numpy as np
np.random.randint(10, size = (5,4))

array([[7, 8, 9, 9],
       [4, 2, 1, 2],
       [8, 5, 8, 7],
       [9, 3, 3, 7],
       [7, 1, 7, 6]])

In [51]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.0603571 , -0.05014891, -0.07601976,  0.03735607,  0.05437382,
        0.08304217,  0.03800426,  0.07953924,  0.05206503, -0.23392813])

In [52]:
print(np.hsplit(matrix, 3))        # split matrix into 3 parts in horizontal direction

[array([[0.68946336, 0.18540372],
       [0.52254447, 0.21027979]]), array([[0.84345207, 0.61759125],
       [0.42146907, 0.15173056]]), array([[0.4296455 , 0.53713882],
       [0.43080623, 0.32991653]])]


In [53]:
print(np.hsplit(matrix, (3,4)))    # split matrix in the 3rd and 4th space in horizontal direction

[array([[0.68946336, 0.18540372, 0.84345207],
       [0.52254447, 0.21027979, 0.42146907]]), array([[0.61759125],
       [0.15173056]]), array([[0.4296455 , 0.53713882],
       [0.43080623, 0.32991653]])]


# Mathematic Operation

In [54]:
A = np.array([20, 39, 40, 50])
B = np.arange(4)
print('A:', A)
print('B:', B)

A: [20 39 40 50]
B: [0 1 2 3]


In [55]:
print('A - B = ', A - B)

A - B =  [20 38 38 47]


In [56]:
print('A - 1 = ', A - 1)

A - 1 =  [19 38 39 49]


In [57]:
array = [1, 2, 3, 4, 5]
print(array)
print(array + 1)

[1, 2, 3, 4, 5]


TypeError: can only concatenate list (not "int") to list

In [ ]:
print('B ^ 2 = ', B ** 2)

In [ ]:
print('e ^ B = ', np.exp(B))

In [ ]:
print('sqrt(B) = ', np.sqrt(B))

In [ ]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
print(A * B)                     # multiplication of corresponding elements

In [ ]:
print(A.dot(B))                  # matrix multiplicaiton

In [ ]:
print(np.dot(A,B))

# Logistic Operation

In [ ]:
vector = np.array([5, 10, 15, 20])
print(vector)

In [ ]:
print(vector == 10)

In [ ]:
print((vector == 10) & (vector == 15))

In [ ]:
print((vector == 10) | (vector == 15))

In [ ]:
equal_to_10 = (vector == 10)
print(equal_to_10)

In [ ]:
print(vector[equal_to_10])

In [ ]:
matrix = np.array([[1,3], [2,5], [9,0]])
print(matrix)

In [ ]:
second_column_5 = (matrix[:,1] == 5)
print(second_column_5)

In [ ]:
print(matrix[second_column_5, :])